services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PYTHONPATH: /app
      PROJECT_ROOT: /app
      ENABLE_MONITORING: ${ENABLE_MONITORING:-1}
      AUTO_MIGRATE: ${AUTO_MIGRATE:-1}
      RUN_TIMEZONE_CHECK: ${RUN_TIMEZONE_CHECK:-1}
      TZ: ${TZ:-Europe/Berlin}
      GRAFANA_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GRAFANA_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GRAFANA_BASE_URL: http://localhost:3000
      GRAFANA_DASHBOARD_UID: ${GRAFANA_DASHBOARD_UID}
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - .:/app   
    depends_on:
      - postgres
      - grafana
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    depends_on:
      - postgres
    restart: always

  grafana-init:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GRAFANA_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GRAFANA_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    volumes:
      - .:/app
    working_dir: /app
    command: python grafana/init.py
    depends_on:
      - grafana
      - postgres
    restart: "no"

volumes:
  postgres_data:
  grafana_data: